### ISSUE TITLE
should go to next iteration only when promise, returned from callback function for prev item is resolved

### ISSUE THREAD

**Issue by ipanasenko** [yoshuawuyts/promise-reduce#1]
Taken from Bluebird documentation: https://github.com/petkaantonov/bluebird/blob/master/API.md#reducefunction-reducer--dynamic-initialvalue---promise

> If the reducer function returns a promise or a thenable, the result for the promise is awaited for before continuing with next iteration.

If you have a look at the example on that page, it will ready next file only when previous file has been successfully read.

You realisation of reduce doesn't seem to support this feature, correct me if I'm wrong.
Following code should output numbers with a second delay between outputs, but it prints them all at the same time:

``` javascript
reduce(function (acc, item) {
  console.log(item);
  return new Promise(function (resolve) {
    setTimeout(resolve, 1000);
  });
}, null)([1, 2, 3, 4]);
```

**Comment by yoshuawuyts** [comment]
Yeah, I've come to the realization that my implementation completely doesn't adhere to what bluebird is doing. That said I think you're right, and the value should be awaited before the next one is executed. Would you be willing to PR it? thanks!

**Comment by ipanasenko** [comment]
Sorry, mate, I didn't create PR, I took some time to play with npm and published new package myself. Never done this before, wanted to know how to do it.
Feel free to take code you need from there, If you want.

Cheers

**Comment by ipanasenko** [comment]
P.S. https://github.com/hottdogg/reduce-for-promises

**Comment by yoshuawuyts** [comment]
@hottdogg no worries! Congrats on your first module! :tada: I'll have a look at your implementation and pull the changes back in, thanks for sharing!
